"""user theme avatar

Revision ID: 31545fdacdbb
Revises: 4f918c7e19fc
Create Date: 2026-08-30 12:49:18.976145

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifikatorlari
revision: str = '31545fdacdbb'
down_revision: str | None = '4f918c7e19fc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('theme', sa.String(length=10), server_default='auto', nullable=False))
    op.add_column('users', sa.Column('avatar_path', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_path')
    op.drop_column('users', 'theme')
    # ### end Alembic commands ###
