"""categories, units, notes, budget

Revision ID: 4f918c7e19fc
Revises: 3ec12d4d0f7a
Create Date: 2026-08-30 11:42:17.207363

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifikatorlari
revision: str = '4f918c7e19fc'
down_revision: str | None = '3ec12d4d0f7a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', 'kind', name='uq_categories_user_name_kind')
    )
    op.create_index('ix_categories_user_id_kind_is_active', 'categories', ['user_id', 'kind', 'is_active'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code', name='uq_units_user_code')
    )
    op.create_table('notes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notes_user_id_project_id_is_pinned', 'notes', ['user_id', 'project_id', 'is_pinned'], unique=False)
    op.create_table('note_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('note_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(length=300), nullable=False),
    sa.Column('is_done', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('entries', sa.Column('is_billable', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('entries', sa.Column('is_rework', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('entries', sa.Column('payment_method', sa.String(length=20), nullable=True))
    op.add_column('entries', sa.Column('vendor', sa.String(length=200), nullable=True))
    # Pul qoidalari — DB darajasidagi backstop (autogenerate CHECK'ni ko'rmaydi)
    op.create_check_constraint(
        'ck_entries_rework_not_billable', 'entries',
        'NOT (is_rework AND is_billable)',
    )
    op.create_check_constraint(
        'ck_entries_master_expense_not_billable', 'entries',
        "NOT (kind = 'expense' AND paid_by = 'master' AND is_billable)",
    )
    op.create_check_constraint(
        'ck_entries_work_no_payment_fields', 'entries',
        "kind <> 'work' OR (payment_method IS NULL AND vendor IS NULL)",
    )
    op.add_column('payments', sa.Column('purpose', sa.String(length=20), server_default='labor', nullable=False))
    op.create_index('ix_payments_project_id_purpose_paid_at', 'payments', ['project_id', 'purpose', 'paid_at'], unique=False)
    op.add_column('price_items', sa.Column('category_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        'fk_price_items_category_id', 'price_items', 'categories',
        ['category_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_price_items_category_id', 'price_items', type_='foreignkey')
    op.drop_column('price_items', 'category_id')
    op.drop_index('ix_payments_project_id_purpose_paid_at', table_name='payments')
    op.drop_column('payments', 'purpose')
    op.drop_constraint('ck_entries_work_no_payment_fields', 'entries', type_='check')
    op.drop_constraint('ck_entries_master_expense_not_billable', 'entries', type_='check')
    op.drop_constraint('ck_entries_rework_not_billable', 'entries', type_='check')
    op.drop_column('entries', 'vendor')
    op.drop_column('entries', 'payment_method')
    op.drop_column('entries', 'is_rework')
    op.drop_column('entries', 'is_billable')
    op.drop_table('note_items')
    op.drop_index('ix_notes_user_id_project_id_is_pinned', table_name='notes')
    op.drop_table('notes')
    op.drop_table('units')
    op.drop_index('ix_categories_user_id_kind_is_active', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
